# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r_packages:
  - covr
bioc_packages:
  - Biobase
  - AnnotationDbi
  - clusterProfiler
  - GEOquery
  - STRINGdb
  - WGCNA
git:
  submodules: false
warnings_are_errors: false
after_success:
  - Rscript -e 'library(covr); codecov()'
